name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  clippy-check:
    name: clippy-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/clippy-check@v1
      with:
        name: clippy-check
        token: ${{ secrets.GITHUB_TOKEN }}
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: avto-dev/markdown-lint@v1
      with:
        args: "**/*.md"
  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ibiqlik/action-yamllint@v3
