name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  clippy-lint:
    name: clippy-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/clippy-check@v1
      with:
        name: clippy-summary
        token: ${{ secrets.GITHUB_TOKEN }}
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v10
      with:
        globs: "**/*.md"
  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ibiqlik/action-yamllint@v3
